you will be navigated to the address of os-code when you click on the text which is present in the footer section
OSCode-Community/OSCodeCommunitySite pull request #507
Opened 2023-05-30 17:07 UTC by Bharath-KumarReddy

In the footer section the os code text is underlined which is a link when you click on it then that address will open in google maps where you can clearly see the address .

like this 

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/24015e7b-5020-4a81-a063-ee9b82dbbbd0)

after clicking ----

![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/009c9d7f-65f9-46c0-a39c-a351c26328b2)

Please Consider this under GSS0C_23 --- [ contributor]  : )

2023-05-30 17:08 UTC, Bharath-KumarReddy commented
@OSCode-Community once check this  : )

2023-05-31 12:05 UTC, akshathar-navada requested changes
Hey @Bharath-KumarReddy , can u pls remove that underline decoration! Let that be normal white color text

2023-05-31 12:21 UTC, Bharath-KumarReddy commented
@akshathar-navada        sure  here  it  is  ----  the text is in normal white color text and not underlined but when you click on that text then that address will open in google maps 


![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/0fc56361-bcc5-493a-8cd0-b753ba5c5f5b)


after  clicking on the  text ----


![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127650446/2de3a19e-fc78-4f35-b4d7-4889ff19a423)

2023-05-31 13:03 UTC, akshathar-navada commented
As this issue was raised by other person, I have assigned it to him

2023-05-31 13:03 UTC, closed without merging